language: python
matrix:
  include:
  - python: '2.7'
    env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.17 matplotlib=1.4 pillow<3 pandas=0.16
      scikit-image=0.11 pyyaml numba=0.20 pytables"
  - python: '3.5'
    env: DEPS="libgfortran=1.0 numpy scipy matplotlib pillow<3 pandas scikit-image
      pyyaml numba pytables"
  - python: '3.6'
    env: DEPS="libgfortran=1.0 numpy scipy matplotlib pandas scikit-image pyyaml numba
      pytables"
addons:
  apt:
    packages:
    - libfftw3-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - gfortran
install:
- conda update --yes conda
- conda config --add channels soft-matter
- conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- echo $PATH
- which python
- conda info
- conda list
- pip install pyfftw
- python setup.py install
- echo $PATH
- ls -lh
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
script:
- python -m unittest discover src -v -p "*test.py"
deploy:
  provider: pypi
  user: ycasg
  password:
    secure: YXBOlEy4f8RupLwppIaR32IoRGMBhOyRRbRMow9IqULft7BbvhKJPGzD/fBDwDACaHSKG/9EMHRzCearqZwlQUe75RyC4CDGaS9xh2UB99pekngoHmsl3DHqZzt1GbdJOmjBXtAkUV/GuYTI7DBSqRfSREmPPapO3iQEF2vzKexI92Ze4Dw1+UXZQ6uwxChKWIv4WL3TANUbNlRCD2VwWNrhlio3wyL2tAt2pJC4qEzbK9zVenIRJJtW/xmVsJR0OR+BjEOo5MMNmw7G2mbkJ5uZt/k+Gvxetl+8123YiINjGiY000L5Z7IHGzFvitahGVkr96PRm0fKqCk13dRLuH6YLZYGmsJtqz/uyx/te0HHw3XqIiyx+0zPK5+RPdGkn1kvcXI7cDEIGPPnof4bzGjwKUQsIvt5ih4p/q5aT5GwSMKi69P6F3RuTIv6KqutIZeg86hqtiQHP4YIjH+VUmb1O5M4SIX+uroIYuN0y3xbR58U9Tp8lJNOlRITBrUBLTj388J2bPwmbQE7DTU37kU9eMUAezw9hTYtYhINNJh3L3mdw8zETKw3LmGBnAI09PCgGgVRXu5MLsUYJLieeY9EuxmOEYe2xqpqKMwIZsld7UfrNA0iQqvCQPD6BPlnl7SKLy4f0grHFWsD4D3wGRnmXi/+ILTDTe1RSPPBPm4=
  on:
    tags: true
    branch: master
